build yaml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,6 +22,7 @@ jobs:
       name: ${{github.ref}}-${{github.sha}}
       ref: ${{github.ref}}-last
       retention: 5
+      test-results: ${{ github.workspace }}/reports/tests
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
@@ -39,7 +40,7 @@ jobs:
       with:
         name: build-artifact-${{name}}
         path: ${{ github.workspace }}/**/*
-        retention-days: 5
+        retention-days: ${{retention}}
         
     - name: Upload build artifact to ${{ref}}
       uses: actions/upload-artifact@v3
@@ -48,37 +49,36 @@ jobs:
         path: ${{ github.workspace }}/**/*
 
     - name: Test
-      run: dotnet test  --no-build --logger trx --results-directory "test-results"
-
+      run: dotnet test  --no-build --logger trx --results-directory "${{test-results}}"
+      continue-on-error: true
+      
     - name: Process trx reports with default
       if: always()
-      # You may also reference just the major or major.minor version
       uses: im-open/process-dotnet-test-results@v2.3.0
       with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
-
+        ignore-test-failures: true
+        base-directory: ${{test-results}}
+    
     - name: Upload dotnet test results to ${{name}}
       uses: actions/upload-artifact@v3
       with:
-        name: test-results-${{name}}
-        path: test-results/**/*
-        retention-days: retention
+        name: test-results-${{name}}-{{steps.process-trx.outputs.test-outcome}}
+        path: ${{test-results}}/**/*
+        retention-days: ${{retention}}
       if: ${{ always() }}
 
     - name: Upload dotnet test results to ${{ref}}
       uses: actions/upload-artifact@v3
       with:
         name: test-results-${{ref}}
-        path: test-results/**/*
-      if: ${{ always() }}
+        path: ${{test-results}}/**/*
+      if: steps.process-trx.outputs.test-outcome == 'Passed'
 
+    - name: Fail if there were test problems
+      if: steps.process-trx.outputs.test-outcome == 'Failed'
+      run: |
+        echo "There were test failures."
+        exit 1
 
-#    - name: Generate list using Markdown
-#      run: |
-#        echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
-#        echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
-#        echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
-#        echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
-#        echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
-#      if: ${{ always() }}
 
